from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from .manifest import dataset_fingerprint
from .models import SemanticResidualModel
from .paper import paper_summary
from .storage import Store

__all__ = ["dataset_fingerprint", "research_manifest", "source_semantic_models",
           "promotion_decision", "promote_candidate", "champion_status"]


def research_manifest(df: pd.DataFrame, *, horizon: str, config: dict[str, Any], semantic_models: list[str] | None = None) -> dict:
    ts = pd.to_datetime(df["ts"], utc=True) if len(df) and "ts" in df else pd.Series(dtype="datetime64[ns, UTC]")
    return {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dataset_fingerprint": dataset_fingerprint(df),
        "rows": int(len(df)),
        "symbols": sorted(df["symbol"].dropna().astype(str).unique().tolist()) if "symbol" in df else [],
        "from": str(ts.min()) if len(ts) else None,
        "through": str(ts.max()) if len(ts) else None,
        "horizon": horizon,
        "semantic_models": sorted(set(semantic_models or [])),
        "config": config,
    }


def source_semantic_models(store: Store) -> list[str]:
    with store.conn() as c:
        rows = c.execute("SELECT DISTINCT model FROM post_semantics_asset ORDER BY model").fetchall()
    return [str(r[0]) for r in rows]


def promotion_decision(
    report: dict,
    paper: dict,
    *,
    min_closed_trades: int = 100,
    min_profit_factor: float = 1.20,
    max_drawdown: float = -0.10,
    max_top5_profit_share: float = 0.50,
    max_high_drift_features: int = 2,
) -> dict:
    evidence = report.get("evidence_gate", {})
    leakage = report.get("leakage", report.get("leakage_audit", {}))
    drift = report.get("drift", {})
    locked = report.get("locked_holdout", {})
    if not locked and isinstance(report.get("locked_protocol"), dict):
        locked = report["locked_protocol"].get("locked_holdout", {})
    locked_protocol = report.get("locked_protocol", {}) if isinstance(report.get("locked_protocol"), dict) else {}
    holdout_reopened = bool(locked.get("holdout_reopened", False) or locked_protocol.get("governance", {}).get("holdout_reopened", False))
    checks = {
        "locked_holdout_pass": locked.get("status") == "PASS_LOCKED_HOLDOUT" and not holdout_reopened,
        # Observed live/forward data gates entry into paper validation;
        # FORWARD_VALIDATED (post-freeze forward evidence) is strictly stronger.
        "forward_evidence_gate": evidence.get("status") in {"PROMISING_FORWARD_OBSERVED", "PROMISING_FORWARD_VALIDATED"},
        "leakage_audit_clean": bool(leakage.get("ok", False)),
        "paper_trade_count": int(paper.get("closed_trades", 0) or 0) >= min_closed_trades,
        "paper_net_positive": float(paper.get("net_return", 0.0) or 0.0) > 0.0,
        "paper_profit_factor": float(paper.get("profit_factor", 0.0) or 0.0) >= min_profit_factor,
        "paper_drawdown": float(paper.get("max_drawdown", -1.0) if paper.get("max_drawdown") is not None else -1.0) >= max_drawdown,
        "paper_not_outlier_dominated": float(paper.get("top5_profit_share", 1.0) if paper.get("top5_profit_share") is not None else 1.0) <= max_top5_profit_share,
        "drift_acceptable": bool(drift.get("ok", False)) and int(drift.get("high_drift_features", 999) or 0) <= max_high_drift_features,
    }
    return {
        "status": "ELIGIBLE_FOR_CHAMPION" if all(checks.values()) else "KEEP_AS_CANDIDATE",
        "checks": checks,
        "thresholds": {
            "min_closed_trades": min_closed_trades,
            "min_profit_factor": min_profit_factor,
            "max_drawdown": max_drawdown,
            "max_top5_profit_share": max_top5_profit_share,
            "max_high_drift_features": max_high_drift_features,
        },
        "paper": paper,
        "evidence_status": evidence.get("status"),
        "note": "Champion eligibility is a research governance gate, not permission for live-capital execution.",
    }


def promote_candidate(
    *,
    candidate_model: str | Path,
    research_report: str | Path,
    store: Store,
    registry_dir: str | Path,
    force: bool = False,
    **thresholds: Any,
) -> dict:
    model_path = Path(candidate_model)
    report_path = Path(research_report)
    model = SemanticResidualModel.load(model_path)
    report = json.loads(report_path.read_text())
    # Identity binding: the evidence in this report must belong to exactly this
    # model manifest. A report generated by model A can never promote model B.
    locked = report.get("locked_holdout") or report.get("locked_protocol", {}).get("locked_holdout", {})
    report_fp = locked.get("model_fingerprint") or report.get("model_fingerprint")
    if report_fp is not None and report_fp != model.training_fingerprint:
        return {
            "status": "REJECTED_IDENTITY_MISMATCH",
            "model_fingerprint": model.training_fingerprint,
            "report_model_fingerprint": report_fp,
            "promoted": False,
            "note": "The research report was produced by a different model manifest. Regenerate the report against this exact model.",
        }
    artifact_sha256 = hashlib.sha256(model_path.read_bytes()).hexdigest()
    report_artifact = locked.get("model_artifact_sha256") or report.get("model_artifact_sha256")
    if report_artifact is not None and report_artifact != artifact_sha256:
        return {
            "status": "REJECTED_IDENTITY_MISMATCH",
            "model_fingerprint": model.training_fingerprint,
            "model_artifact_sha256": artifact_sha256,
            "report_artifact_sha256": report_artifact,
            "promoted": False,
            "note": "The report references a different model artifact file hash.",
        }
    paper = paper_summary(store, model_fingerprint=model.training_fingerprint)
    decision = promotion_decision(report, paper, **thresholds)
    out = Path(registry_dir); out.mkdir(parents=True, exist_ok=True)
    candidate_meta = {
        "registered_at": datetime.now(timezone.utc).isoformat(),
        "model_path": str(model_path),
        "model_artifact_sha256": artifact_sha256,
        "training_fingerprint": model.training_fingerprint,
        "model_manifest": model.manifest,
        "model_version": model.version,
        "feature_version": model.feature_version,
        "trained_through": model.trained_through,
        "horizon": model.horizon,
        "decision": decision,
        "research_report": str(report_path),
    }
    (out / "latest_candidate.json").write_text(json.dumps(candidate_meta, indent=2, default=str))
    if decision["status"] == "ELIGIBLE_FOR_CHAMPION" or force:
        shutil.copy2(model_path, out / "champion.joblib")
        champion = {**candidate_meta, "promoted_at": datetime.now(timezone.utc).isoformat(), "forced": bool(force)}
        (out / "champion.json").write_text(json.dumps(champion, indent=2, default=str))
        decision = {**decision, "promoted": True, "champion_model": str(out / "champion.joblib")}
    else:
        decision = {**decision, "promoted": False}
    return decision


def champion_status(registry_dir: str | Path) -> dict:
    p = Path(registry_dir) / "champion.json"
    if not p.exists():
        return {"status": "NO_CHAMPION"}
    return {"status": "CHAMPION_PRESENT", **json.loads(p.read_text())}
